In [4]:
import numpy as np

In [22]:
def traditional_multiply_matrix(A, B):
    result = np.zeros((A.shape[0], B.shape[1]))

    k = A.shape[1]

    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            sum_j = 0
            for k in range(A.shape[1]):
                sum_j += A[i, k] * B[k, j]

            result[i, j] = sum_j

    return result

In [3]:
def multiply_matrix(A, B, l):
    try:
        if A.shape[1] != B.shape[0]:
            raise ValueError(
                "Liczba kolumn pierwszej macierzy musi być równa liczbie wierszy drugiej macierzy"
            )

        if (
            A.shape[0] < 2**l
            and A.shape[1] < 2**l
            and B.shape[0] < 2**l
            and B.shape[1] < 2**l
        ):
            return traditional_multiply_matrix(A, B)
    except ValueError as e:
        print(f"Błąd: {e}")

In [29]:
def split_matrix(matrix):
    n = matrix.shape[0] // 2
    return matrix[:n, :n], matrix[:n, n:], matrix[n:, :n], matrix[n:, n:]


def strassen_multiply_matrix(A, B):
    global dod
    global od
    global mno
    if len(A) == 1:
        mno += 1
        return A * B

    A11, A12, A21, A22 = split_matrix(A)
    B11, B12, B21, B22 = split_matrix(B)

    P1 = strassen_multiply_matrix(A11 + A22, B11 + B22)
    P2 = strassen_multiply_matrix(A21 + A22, B11)
    P3 = strassen_multiply_matrix(A11, B12 - B22)
    P4 = strassen_multiply_matrix(A22, B21 - B11)
    P5 = strassen_multiply_matrix(A11 + A12, B22)
    P6 = strassen_multiply_matrix(A21 - A11, B11 + B12)
    P7 = strassen_multiply_matrix(A12 - A22, B21 + B22)
    mno += 7
    dod += 6
    od += 4
    C11 = P1 + P4 - P5 + P7
    C12 = P3 + P5
    C21 = P2 + P4
    C22 = P1 + P3 - P2 + P6
    dod += 6
    od += 2

    C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))

    return C

In [ ]:
import datetime


times = []
for k in range(2, 17):

    start = datetime.datetime.now()
    strassen_multiply_matrix(
        np.random.randint(10, size=(2**k, 2**k)),
        np.random.randint(10, size=(2**k, 2**k)),
    )

    times.append((datetime.datetime.now() - start).total_seconds())
    with open("times.txt", "w+") as f:
        for items in times:
            f.write("%s\n" % items)

KeyboardInterrupt: 

In [58]:
counts = []
for k in range(2, 16):
    dod = od = mno = 0
    strassen_multiply_matrix(
        np.random.randint(10, size=(2**k, 2**k)),
        np.random.randint(10, size=(2**k, 2**k)),
    )
    counts.append(dod)
    counts.append(od)
    counts.append(mno)

    with open("counts.txt", "w+") as f:
        for items in counts:
            f.write("%s\n" % items)

KeyboardInterrupt: 

In [ ]:
import matplotlib.pyplot as plt


lines = []
with open("counts.txt") as file:
    for line in file:
        for word in line.split():
            lines.append(word)


print(lines)
# plt.xlabel("2^n - size of matrix")
# plt.ylabel("Time difference in seconds")
# plt.plot(list(range(2, 17)), times)
# plt.show()

['[96,', '48,', '105]', '[684,', '342,', '742]', '[4800,', '2400,', '5201]', '[33612,', '16806,', '36414]', '[235296,', '117648,', '254905]', '[1647084,', '823542,', '1784342]']


## Tests


In [24]:
A = np.array([[1, 3], [2, 2]])
A

array([[1, 3],
       [2, 2]])

In [25]:
B = np.array([[2, 2], [6, 3]])
B

array([[2, 2],
       [6, 3]])

In [ ]:
print(traditional_multiply_matrix(A, B))
print(strassen_multiply_matrix(A, B))

[[20. 11.]
 [16. 10.]]
[[20 11]
 [16 10]]


In [ ]:
multiply_matrix(A, B, 2)

array([[20., 11.],
       [16., 10.]])

In [ ]:
C = np.array([[1, 2]])
C

array([[1, 2]])

In [ ]:
multiply_matrix(A, C, 2)

Błąd: Liczba kolumn pierwszej macierzy musi być równa liczbie wierszy drugiej macierzy
