In [57]:
import numpy as np

In [58]:
A = np.array([[2, 2, 1, 3], [7, 8, 2, 8], [5, 0, 8, 7], [3, 5, 6, 3], [6, 9, 8, 4]])
n, m = A.shape
print(A)

[[2 2 1 3]
 [7 8 2 8]
 [5 0 8 7]
 [3 5 6 3]
 [6 9 8 4]]


In [59]:
# 2. Proszę obliczyć i wypisać/narysować macierz AA.T
AAT = np.dot(A, A.T)
print("AAT = \n", AAT)
print("AAT shape = ", AAT.shape)


AAT = 
 [[ 18  56  39  31  50]
 [ 56 181 107  97 162]
 [ 39 107 138  84 122]
 [ 31  97  84  79 123]
 [ 50 162 122 123 197]]
AAT shape =  (5, 5)


In [60]:
# 3. Proszę (używając stosownej biblioteki) policzyć wartości λi i
#wektory własne Ui macierzy AAT
eigenvalues, eigenvectors = np.linalg.eig(AAT)

idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

print("Eigenvalues = ", eigenvalues)
print("Eigenvectors = \n", eigenvectors)
print("Shape of eigenvectors (U) = ", eigenvectors.shape)

Eigenvalues =  [ 5.27198727e+02  5.22965267e+01  3.29123797e+01  5.92366606e-01
 -2.64827854e-16]
Eigenvectors = 
 [[ 0.17354228  0.06750887  0.23303841 -0.4040119  -0.86475032]
 [ 0.54275123  0.5240643   0.58684982  0.03444987  0.29188733]
 [ 0.43235249 -0.83173678  0.31478192  0.14364195  0.03955483]
 [ 0.37272532 -0.07348099 -0.39457998 -0.77167806  0.3232584 ]
 [ 0.5911441   0.15366728 -0.58865896  0.46847364 -0.24687667]]
Shape of eigenvectors (U) =  (5, 5)


In [61]:
# 4. Proszę wypisać/narysować macierz wektorów własnych
# [U1U2...Un-1Un] oraz diagonalną S taką że Sii= pierwiastek z λi
U = eigenvectors

S = np.zeros((n, m))
for i in range(min(n, m)):
    S[i, i] = np.sqrt(eigenvalues[i]) if eigenvalues[i] > 1e-10 else 0.0
print("S = \n", S)
print("S shape = ", S.shape)

S = 
 [[22.9608085   0.          0.          0.        ]
 [ 0.          7.23163375  0.          0.        ]
 [ 0.          0.          5.73693121  0.        ]
 [ 0.          0.          0.          0.76965356]
 [ 0.          0.          0.          0.        ]]
S shape =  (5, 4)


In [62]:
# 5. Proszę obliczy macierz V korzystając z własności V=ATUS-1
# 6. Proszę wypisać/narysować macierz [V1V2...V-m-1Vm]T(wierszami)
S_inv = np.zeros_like(S)
for i in range(m):
    if S[i, i] > 1e-10:
        S_inv[i, i] = 1.0 / S[i, i]

V = A.T @ U @ S_inv
print("V.T = \n", V.T)

V.T = 
 [[ 0.47790765  0.51709929  0.50883963  0.49527247]
 [ 0.047893    0.73885555 -0.65680932 -0.14282946]
 [ 0.24965289 -0.36778463 -0.54938051  0.70752311]
 [ 0.84082339 -0.22679343 -0.08868373 -0.48344179]]


In [63]:
reconstructed_A_v1 = U @ S @ V.T
reconstructed_A_v1

array([[2.00000000e+00, 2.00000000e+00, 1.00000000e+00, 3.00000000e+00],
       [7.00000000e+00, 8.00000000e+00, 2.00000000e+00, 8.00000000e+00],
       [5.00000000e+00, 5.86468211e-15, 8.00000000e+00, 7.00000000e+00],
       [3.00000000e+00, 5.00000000e+00, 6.00000000e+00, 3.00000000e+00],
       [6.00000000e+00, 9.00000000e+00, 8.00000000e+00, 4.00000000e+00]])

In [64]:
ATA = np.dot(A.T, A)

print(ATA)

[[123 129 122 130]
 [129 174 120 121]
 [122 120 169 125]
 [130 121 125 147]]


In [65]:
lambdas, V = np.linalg.eig(ATA)
print("\nStep 8: Eigenvalues (λ_i) of A^T A:")
print(lambdas)
print("\nEigenvectors (V_i) of A^T A (columns):")
print(V)


Step 8: Eigenvalues (λ_i) of A^T A:
[527.19872691   0.59236661  32.91237974  52.29652675]

Eigenvectors (V_i) of A^T A (columns):
[[ 0.47790765  0.84082339  0.24965289 -0.047893  ]
 [ 0.51709929 -0.22679343 -0.36778463 -0.73885555]
 [ 0.50883963 -0.08868373 -0.54938051  0.65680932]
 [ 0.49527247 -0.48344179  0.70752311  0.14282946]]


In [66]:
print("\n9. Macierz V^T:\n", V.T)


9. Macierz V^T:
 [[ 0.47790765  0.51709929  0.50883963  0.49527247]
 [ 0.84082339 -0.22679343 -0.08868373 -0.48344179]
 [ 0.24965289 -0.36778463 -0.54938051  0.70752311]
 [-0.047893   -0.73885555  0.65680932  0.14282946]]


In [67]:
S = np.zeros((m, m))
for i in range(m):
    S[i, i] = np.sqrt(lambdas[i]) if lambdas[i] > 1e-10 else 0.0
print("\nStep 9: Diagonal S (manual):\n", S)


Step 9: Diagonal S (manual):
 [[22.9608085   0.          0.          0.        ]
 [ 0.          0.76965356  0.          0.        ]
 [ 0.          0.          5.73693121  0.        ]
 [ 0.          0.          0.          7.23163375]]


In [68]:
S_inv = np.zeros_like(S)
for i in range(m):
    if S[i, i] > 1e-10:
        S_inv[i, i] = 1.0 / S[i, i]

U = A @ V @ S_inv
print("\nStep 11: U = [U_1 U_2 ... U_m]:\n", U)


Step 11: U = [U_1 U_2 ... U_m]:
 [[ 0.17354228 -0.4040119   0.23303841 -0.06750887]
 [ 0.54275123  0.03444987  0.58684982 -0.5240643 ]
 [ 0.43235249  0.14364195  0.31478192  0.83173678]
 [ 0.37272532 -0.77167806 -0.39457998  0.07348099]
 [ 0.5911441   0.46847364 -0.58865896 -0.15366728]]


In [69]:
reconstructed_A = U @ S @ V.T
print(
    "\nStep 12: Reconstructed A (should match original A):\n",
    "Using AAT decomposition:\n",
    reconstructed_A_v1,
    "\n\n",
    "Using ATA decomposition:\n",
    reconstructed_A,
    "\n\n",
    "Original A:\n",
    A,
)


Step 12: Reconstructed A (should match original A):
 Using AAT decomposition:
 [[2.00000000e+00 2.00000000e+00 1.00000000e+00 3.00000000e+00]
 [7.00000000e+00 8.00000000e+00 2.00000000e+00 8.00000000e+00]
 [5.00000000e+00 5.86468211e-15 8.00000000e+00 7.00000000e+00]
 [3.00000000e+00 5.00000000e+00 6.00000000e+00 3.00000000e+00]
 [6.00000000e+00 9.00000000e+00 8.00000000e+00 4.00000000e+00]] 

 Using ATA decomposition:
 [[ 2.00000000e+00  2.00000000e+00  1.00000000e+00  3.00000000e+00]
 [ 7.00000000e+00  8.00000000e+00  2.00000000e+00  8.00000000e+00]
 [ 5.00000000e+00 -1.77635684e-15  8.00000000e+00  7.00000000e+00]
 [ 3.00000000e+00  5.00000000e+00  6.00000000e+00  3.00000000e+00]
 [ 6.00000000e+00  9.00000000e+00  8.00000000e+00  4.00000000e+00]] 

 Original A:
 [[2 2 1 3]
 [7 8 2 8]
 [5 0 8 7]
 [3 5 6 3]
 [6 9 8 4]]


In [70]:
from numpy.linalg import matrix_rank


rank_A = np.sum(lambdas > 1e-10)
nullity_A = m - rank_A
print("\nStep 13: Dimensions:")
print(f"dim(R(A)) = rank(A) = {rank_A}")
print(matrix_rank(A))

print(f"dim(N(A)) = nullity(A) = {nullity_A}")


Step 13: Dimensions:
dim(R(A)) = rank(A) = 4
4
dim(N(A)) = nullity(A) = 0
